on:
    workflow_dispatch:
    push:
        branches:
            - main
            - production
            - deploy-pull-request
    pull_request:
        types: [ opened, synchronize, reopened ]

jobs:
    variables:
        runs-on: ubuntu-latest
        outputs:
            ENVIRONMENT: ${{ fromJson(steps.variables.outputs.result).ENVIRONMENT }}
            TAG: ${{ fromJson(steps.variables.outputs.result).TAG }}

            # backend
            BACKEND_DOMAIN: ${{ fromJson(steps.variables.outputs.result).BACKEND_DOMAIN }}
            BACKEND_URL: ${{ fromJson(steps.variables.outputs.result).BACKEND_URL }}
            TRAEFIK_BACKEND_CERT: ${{ fromJson(steps.variables.outputs.result).TRAEFIK_BACKEND_CERT }}
            CORS_ORIGIN_PATTERN: ${{ fromJson(steps.variables.outputs.result).CORS_ORIGIN_PATTERN }}

            # static site
            ZENMO_DOMAIN: ${{ fromJson(steps.variables.outputs.result).ZENMO_DOMAIN }}
            LUX_DOMAIN: ${{ fromJson(steps.variables.outputs.result).LUX_DOMAIN }}
            SUBDOMAIN_SEPARATOR: ${{ fromJson(steps.variables.outputs.result).SUBDOMAIN_SEPARATOR }}

            # traefik
            TRAEFIK_ZENMO_MAIN_CERT: ${{ fromJson(steps.variables.outputs.result).TRAEFIK_ZENMO_MAIN_CERT }}
            TRAEFIK_LUX_MAIN_CERT: ${{ fromJson(steps.variables.outputs.result).TRAEFIK_LUX_MAIN_CERT }}
            TRAEFIK_LUX_SANS_CERT: ${{ fromJson(steps.variables.outputs.result).TRAEFIK_LUX_SANS_CERT }}
            TRAEFIK_LUX_HOST_REGEXP: ${{ fromJson(steps.variables.outputs.result).TRAEFIK_LUX_HOST_REGEXP }}
            TRAEFIK_PRIORITY: ${{ fromJson(steps.variables.outputs.result).TRAEFIK_PRIORITY }}

            SSH_HOST: ${{ fromJson(steps.variables.outputs.result).SSH_HOST }}
            SSH_HOST_ED25519_PUBLIC_KEY: ${{ fromJson(steps.variables.outputs.result).SSH_HOST_ED25519_PUBLIC_KEY }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Variables
                uses: actions/github-script@v7
                id: variables
                with:
                    script: |
                        const getVariables = require('./.github/workflows/get-variables/index.js')
                        return getVariables(context)

    build-static:
        needs:
            - variables
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            ## Buildx is needed for caching
            -   name: Set up Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            # exposes ACTIONS_CACHE_URL and ACTIONS_RUNTIME_TOKEN
            # see https://docs.docker.com/build/cache/backends/gha/
            -   name: Expose
                uses: crazy-max/ghaction-github-runtime@v3

            -   run: ./deploy/static/build.sh --push
                env:
                    BACKEND_URL: ${{ needs.variables.outputs.BACKEND_URL }}
                    ZENMO_DOMAIN: ${{ needs.variables.outputs.ZENMO_DOMAIN }}
                    LUX_DOMAIN: ${{ needs.variables.outputs.LUX_DOMAIN }}
                    TAG: ${{ needs.variables.outputs.TAG }}


    build-backend:
        needs:
            - variables
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    submodules: true
                    token: ${{ secrets.LUX_WEBSITE_PRIVATE_PAT }}

            ## Buildx is needed for caching
            -   name: Set up Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            # exposes ACTIONS_CACHE_URL and ACTIONS_RUNTIME_TOKEN
            # see https://docs.docker.com/build/cache/backends/gha/
            -   name: Expose
                uses: crazy-max/ghaction-github-runtime@v3

            -   run: ./deploy/backend/build.sh --push
                env:
                    BACKEND_URL: ${{ needs.variables.outputs.BACKEND_URL }}
                    ZENMO_DOMAIN: ${{ needs.variables.outputs.ZENMO_DOMAIN }}
                    LUX_DOMAIN: ${{ needs.variables.outputs.LUX_DOMAIN }}
                    SUBDOMAIN_SEPARATOR: ${{ needs.variables.outputs.SUBDOMAIN_SEPARATOR }}
                    TAG: ${{ needs.variables.outputs.TAG }}

    deploy:
        needs:
            - build-backend
            - build-static
            - variables
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.PODHOST_SSH_PRIVATE_KEY }}
                    known_hosts: ${{ needs.variables.outputs.SSH_HOST }} ssh-ed25519 ${{ needs.variables.outputs.SSH_HOST_ED25519_PUBLIC_KEY }}
            -   run: ./deploy/quadlets/deploy.sh
                env:
                    ENVIRONMENT: ${{ needs.variables.outputs.ENVIRONMENT }}
                    TAG: ${{ needs.variables.outputs.TAG }}

                    # Backend
                    BACKEND_DOMAIN: ${{ needs.variables.outputs.BACKEND_DOMAIN }}
                    BACKEND_URL: ${{ needs.variables.outputs.BACKEND_URL }}
                    TRAEFIK_BACKEND_CERT: ${{ needs.variables.outputs.TRAEFIK_BACKEND_CERT }}
                    CORS_ORIGIN_PATTERN: ${{ needs.variables.outputs.CORS_ORIGIN_PATTERN }}

                    # Traefik
                    LUX_DOMAIN: ${{ needs.variables.outputs.LUX_DOMAIN }}
                    ZENMO_DOMAIN: ${{ needs.variables.outputs.ZENMO_DOMAIN }}
                    TRAEFIK_ZENMO_MAIN_CERT: ${{ needs.variables.outputs.TRAEFIK_ZENMO_MAIN_CERT }}
                    TRAEFIK_LUX_MAIN_CERT: ${{ needs.variables.outputs.TRAEFIK_LUX_MAIN_CERT }}
                    TRAEFIK_LUX_SANS_CERT: ${{ needs.variables.outputs.TRAEFIK_LUX_SANS_CERT }}
                    TRAEFIK_LUX_HOST_REGEXP: ${{ needs.variables.outputs.TRAEFIK_LUX_HOST_REGEXP }}
                    TRAEFIK_PRIORITY: ${{ needs.variables.outputs.TRAEFIK_PRIORITY }}

                    SSH_HOST: ${{ needs.variables.outputs.SSH_HOST }}
            -   name: Comment on PR
                if: ${{ github.event_name == 'pull_request' }}
                uses: actions/github-script@v7
                env:
                    ZENMO_DOMAIN: ${{ needs.variables.outputs.ZENMO_DOMAIN }}
                    LUX_DOMAIN: ${{ needs.variables.outputs.LUX_DOMAIN }}
                with:
                    script: |
                        const body = [
                          'The site has been deployed:',
                          '',
                          `- https://${process.env.ZENMO_DOMAIN}`,
                          `- https://${process.env.LUX_DOMAIN}`,
                        ].join('\n')
                        
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.issue.number,
                          body,
                        })
